### ISSUE TITLE
Shall we use typescript-eslint-parser?

### ISSUE THREAD

**Issue by moltar** [daveberning/nuxt-starter-varia#5]
Right now the project uses `babel-eslint` in `.eslintrc.js`, but it seems to not work correctly inside components. TypeScript syntax is marked as invalid.

Replacing with `typescript-eslint-parser` seems to solve the problem.

But I am kinda vague on how all of this linting works, especially with TS.

**Comment by moltar** [comment]
I do see that it throws a warning now:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~3.1.1

YOUR TYPESCRIPT VERSION: 3.2.2

Please only submit bug reports when using the officially supported version.

=============
```

**Comment by daveberning** [comment]
Roman, can you elaborate more?  Can you provide an example? I don't see any TypeScript errors on my end. Thanks.

**Comment by moltar** [comment]
Here is an example: https://github.com/moltar/nuxt-starter-varia/tree/ts-fail-example

See the last commit on that branch.

Then run linter: `npm run lint`

Result:

```
❯ npm run lint

> nuxt-starter-ts@1.0.0 lint .../nuxt-starter-varia
> eslint --ext .js,.vue --ignore-path .gitignore .


.../nuxt-starter-varia/pages/index.vue
  48:2  error  Parsing error: Unexpected token, expected ";"

   8 |   text: "test",
   9 |   url: ""
> 10 | } as Link;
     |   ^
  11 |
  12 | @Component({
  13 |   components: {

✖ 1 problem (1 error, 0 warnings)
```

**Comment by daveberning** [comment]
I did the following...

`vue init daveberning/nuxt-starter-varia varia-test`
`yarn`
`yarn dev` (dev server runs, works)

`yarn lint`

I got no errors. Can you confirm that you are no longer getting errors? Thanks!

**Comment by moltar** [comment]
The linting errors are still there.

Notice that I introduced the extra code to the file, which is valid TypeScript and causes the linting errors.

There are no linting errors in the default template code.

https://github.com/daveberning/nuxt-starter-varia/compare/master...moltar:ts-fail-example#diff-b19fa22add3de9cd0b98b05366479d92R45

The code is:

```ts
 const foo = {
   text: "test",
   url: ""
 } as Link;
```

**Comment by daveberning** [comment]
Published under [v1.1.1](https://github.com/daveberning/nuxt-starter-varia/releases/tag/1.1.1). Thanks for the help!

**Comment by moltar** [comment]
I think you forgot to include `typescript-eslint-parser` as a dep to `package.json`.

**Comment by daveberning** [comment]
Got, it. Thanks!
